import { useEffect, useRef, useState, type ChangeEvent, type PointerEvent } from 'react'
import { Download, ImagePlus, LoaderCircle, RotateCcw } from 'lucide-react'
import { useParams } from 'react-router-dom'
import { publicApi, type PublicFramePayload } from '../../lib/api'

const W = 1080, H = 1920
function drawCover(ctx: CanvasRenderingContext2D, img: HTMLImageElement, zoom: number, pan: {x:number;y:number}) {
  const base = Math.max(W/img.width,H/img.height), scale=base*zoom, dw=img.width*scale, dh=img.height*scale
  ctx.drawImage(img,(W-dw)/2+pan.x,(H-dh)/2+pan.y,dw,dh)
}
function ornament(ctx: CanvasRenderingContext2D,x:number,y:number,s=1){ctx.save();ctx.translate(x,y);ctx.scale(s,s);ctx.strokeStyle='rgba(246,232,198,.92)';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,34,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(-70,0);ctx.quadraticCurveTo(-35,-42,0,0);ctx.quadraticCurveTo(35,42,70,0);ctx.stroke();ctx.beginPath();ctx.moveTo(0,-70);ctx.quadraticCurveTo(42,-35,0,0);ctx.quadraticCurveTo(-42,35,0,70);ctx.stroke();ctx.restore()}

export function PublicFramePage(){
  const { slug='' }=useParams(); const canvasRef=useRef<HTMLCanvasElement>(null); const imageRef=useRef<HTMLImageElement|null>(null); const dragRef=useRef<any>(null)
  const [settings,setSettings]=useState<PublicFramePayload|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [imageUrl,setImageUrl]=useState(''); const [zoom,setZoom]=useState(1); const [pan,setPan]=useState({x:0,y:0})
  useEffect(()=>{publicApi.getFrame(slug).then(setSettings).catch(e=>setError(e instanceof Error?e.message:'Frame tidak ditemukan.')).finally(()=>setLoading(false))},[slug])
  useEffect(()=>{const canvas=canvasRef.current,ctx=canvas?.getContext('2d');if(!ctx||!settings)return;ctx.clearRect(0,0,W,H);const g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,'#a99b87');g.addColorStop(1,'#4b6257');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);if(imageRef.current?.complete&&imageRef.current.naturalWidth)drawCover(ctx,imageRef.current,zoom,pan);ctx.fillStyle=`rgba(13,37,29,${settings.frameOverlay/100})`;ctx.fillRect(0,0,W,H);ctx.textAlign='center';if(settings.framePreset==='heritage'){ctx.strokeStyle='rgba(246,232,198,.92)';ctx.lineWidth=4;ctx.strokeRect(42,42,W-84,H-84);ctx.strokeRect(62,62,W-124,H-124);ornament(ctx,W/2,190,1.05);ornament(ctx,W/2,H-190,.8);ctx.fillStyle='#f6e8c6';ctx.font='36px Georgia';ctx.fillText('THE WEDDING OF',W/2,390);ctx.font='italic 96px Georgia';ctx.fillText(settings.frameNames,W/2,505);ctx.font='34px Arial';ctx.fillText(settings.frameDateLabel,W/2,570)}else if(settings.framePreset==='botanical'){ctx.strokeStyle='rgba(242,238,220,.9)';ctx.lineWidth=3;ctx.beginPath();ctx.arc(W/2,270,420,Math.PI,0);ctx.stroke();ctx.strokeRect(78,270,W-156,H-355);ctx.fillStyle='#f5efdf';ctx.font='28px Arial';ctx.fillText('CELEBRATING LOVE',W/2,380);ctx.font='italic 104px Georgia';ctx.fillText(settings.frameNames,W/2,505);ctx.font='32px Arial';ctx.fillText(settings.frameDateLabel,W/2,565)}else{ctx.fillStyle='rgba(250,248,242,.92)';ctx.fillRect(70,70,W-140,260);ctx.fillRect(70,H-270,W-140,200);ctx.fillStyle='#173b30';ctx.textAlign='left';ctx.font='28px Arial';ctx.fillText('IINVITATION / WEDDING FRAME',110,130);ctx.font='78px Georgia';ctx.fillText(settings.frameNames,110,240);ctx.font='30px Arial';ctx.fillText(settings.frameDateLabel,110,H-165);ctx.textAlign='right';ctx.fillText('CELEBRATE · CAPTURE · SHARE',W-110,H-165)}},[settings,imageUrl,zoom,pan])
  const loadFile=(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;const url=URL.createObjectURL(file);const img=new Image();img.onload=()=>{imageRef.current=img;setImageUrl(url);setZoom(1);setPan({x:0,y:0})};img.src=url}
  const point=(e:PointerEvent<HTMLCanvasElement>)=>{const r=canvasRef.current!.getBoundingClientRect();return{x:(e.clientX-r.left)*(W/r.width),y:(e.clientY-r.top)*(H/r.height)}}
  const start=(e:PointerEvent<HTMLCanvasElement>)=>{if(!imageRef.current)return;dragRef.current={p:point(e),pan};e.currentTarget.setPointerCapture?.(e.pointerId)}
  const move=(e:PointerEvent<HTMLCanvasElement>)=>{if(!dragRef.current)return;const p=point(e);setPan({x:dragRef.current.pan.x+p.x-dragRef.current.p.x,y:dragRef.current.pan.y+p.y-dragRef.current.p.y})}
  const download=()=>{if(!canvasRef.current)return;const a=document.createElement('a');a.download=`iinvitation-frame-${slug}.png`;a.href=canvasRef.current.toDataURL('image/png',1);a.click()}
  if(loading)return <main className="public-state"><LoaderCircle className="spin"/><h1>Memuat Wedding Frame...</h1></main>
  if(error||!settings)return <main className="public-state"><h1>Wedding Frame tidak tersedia</h1><p>{error}</p></main>
  return <main className="public-frame-shell"><header><div className="guestbook-public-brand"><span>I</span><div><strong>Iinvitation</strong><small>Wedding Frame</small></div></div><div><span>{settings.clientName}</span><strong>{settings.frameNames}</strong></div></header><div className="public-frame-content"><section className="public-frame-controls"><span className="eyebrow">Create & Share</span><h1>Abadikan momenmu.</h1><p>Upload foto, geser langsung di frame, atur zoom, lalu download PNG siap Instagram Story atau WhatsApp.</p><label className="public-frame-upload"><input type="file" accept="image/*" onChange={loadFile}/><ImagePlus size={20}/><span>{imageUrl?'Ganti foto':'Upload foto'}</span></label><label>Zoom <b>{zoom.toFixed(2)}x</b><input type="range" min="1" max="2.7" step=".01" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label><div className="public-frame-actions"><button onClick={()=>{setZoom(1);setPan({x:0,y:0})}}><RotateCcw size={16}/> Reset</button><button className="primary" disabled={!imageUrl} onClick={download}><Download size={16}/> Download PNG</button></div><small>Preset frame dipilih oleh admin untuk klien ini: <b>{settings.framePreset}</b>.</small></section><section className="public-frame-canvas-area"><div className="public-frame-phone"><canvas ref={canvasRef} width={W} height={H} onPointerDown={start} onPointerMove={move} onPointerUp={()=>dragRef.current=null} onPointerCancel={()=>dragRef.current=null}/>{!imageUrl&&<div className="public-frame-empty"><ImagePlus size={34}/><strong>Upload your photo</strong><span>Foto tidak diunggah ke server. Semua proses terjadi di browser.</span></div>}</div><p>Drag foto pada preview untuk mengatur framing.</p></section></div></main>
}
